# Generated by Django 5.2.6 on 2025-11-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='proudcts/default.png', null=True, upload_to='products/'),
        ),
    ]
