# Generated by Django 5.2.6 on 2025-11-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Numeric quantity (e.g 1.5 for 1.5kg or 2 for 2 pieces )', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('ltr', 'Litres'), ('pkt', 'Packet'), ('jar', 'Jar')], default='pcs', max_length=10),
        ),
    ]
