# Generated by Django 5.2.6 on 2025-12-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_payment_method_order_status_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('shipped', 'Shipped'), ('out_for_delivery', 'out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
    ]
